# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

from . import feature_pb2 as feature__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rexample.proto\x12\x0e\x64\x61ta_serialize\x1a\rfeature.proto\"5\n\x07\x45xample\x12*\n\x08\x66\x65\x61tures\x18\x01 \x01(\x0b\x32\x18.data_serialize.Features\"q\n\x0fSequenceExample\x12)\n\x07\x63ontext\x18\x01 \x01(\x0b\x32\x18.data_serialize.Features\x12\x33\n\rfeature_lists\x18\x02 \x01(\x0b\x32\x1c.data_serialize.FeatureListsb\x06proto3')



_EXAMPLE = DESCRIPTOR.message_types_by_name['Example']
_SEQUENCEEXAMPLE = DESCRIPTOR.message_types_by_name['SequenceExample']
Example = _reflection.GeneratedProtocolMessageType('Example', (_message.Message,), {
  'DESCRIPTOR' : _EXAMPLE,
  '__module__' : 'example_pb2'
  # @@protoc_insertion_point(class_scope:data_serialize.Example)
  })
_sym_db.RegisterMessage(Example)

SequenceExample = _reflection.GeneratedProtocolMessageType('SequenceExample', (_message.Message,), {
  'DESCRIPTOR' : _SEQUENCEEXAMPLE,
  '__module__' : 'example_pb2'
  # @@protoc_insertion_point(class_scope:data_serialize.SequenceExample)
  })
_sym_db.RegisterMessage(SequenceExample)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EXAMPLE._serialized_start=48
  _EXAMPLE._serialized_end=101
  _SEQUENCEEXAMPLE._serialized_start=103
  _SEQUENCEEXAMPLE._serialized_end=216
# @@protoc_insertion_point(module_scope)
