# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: example.proto
# Protobuf Python Version: 5.27.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    0,
    '',
    'example.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import feature_pb2 as feature__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rexample.proto\x12\x0e\x64\x61ta_serialize\x1a\rfeature.proto\"5\n\x07\x45xample\x12*\n\x08\x66\x65\x61tures\x18\x01 \x01(\x0b\x32\x18.data_serialize.Features\"q\n\x0fSequenceExample\x12)\n\x07\x63ontext\x18\x01 \x01(\x0b\x32\x18.data_serialize.Features\x12\x33\n\rfeature_lists\x18\x02 \x01(\x0b\x32\x1c.data_serialize.FeatureListsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXAMPLE']._serialized_start=48
  _globals['_EXAMPLE']._serialized_end=101
  _globals['_SEQUENCEEXAMPLE']._serialized_start=103
  _globals['_SEQUENCEEXAMPLE']._serialized_end=216
# @@protoc_insertion_point(module_scope)
