# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: feature.proto
# Protobuf Python Version: 5.27.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    0,
    '',
    'feature.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rfeature.proto\x12\x0e\x64\x61ta_serialize\"\x1a\n\tBytesList\x12\r\n\x05value\x18\x01 \x03(\x0c\"\x1e\n\tFloatList\x12\x11\n\x05value\x18\x01 \x03(\x02\x42\x02\x10\x01\"\x1e\n\tInt64List\x12\x11\n\x05value\x18\x01 \x03(\x03\x42\x02\x10\x01\"\xa4\x01\n\x07\x46\x65\x61ture\x12/\n\nbytes_list\x18\x01 \x01(\x0b\x32\x19.data_serialize.BytesListH\x00\x12/\n\nfloat_list\x18\x02 \x01(\x0b\x32\x19.data_serialize.FloatListH\x00\x12/\n\nint64_list\x18\x03 \x01(\x0b\x32\x19.data_serialize.Int64ListH\x00\x42\x06\n\x04kind\"\x8b\x01\n\x08\x46\x65\x61tures\x12\x36\n\x07\x66\x65\x61ture\x18\x01 \x03(\x0b\x32%.data_serialize.Features.FeatureEntry\x1aG\n\x0c\x46\x65\x61tureEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.data_serialize.Feature:\x02\x38\x01\"7\n\x0b\x46\x65\x61tureList\x12(\n\x07\x66\x65\x61ture\x18\x01 \x03(\x0b\x32\x17.data_serialize.Feature\"\xa4\x01\n\x0c\x46\x65\x61tureLists\x12\x43\n\x0c\x66\x65\x61ture_list\x18\x01 \x03(\x0b\x32-.data_serialize.FeatureLists.FeatureListEntry\x1aO\n\x10\x46\x65\x61tureListEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12*\n\x05value\x18\x02 \x01(\x0b\x32\x1b.data_serialize.FeatureList:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'feature_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FLOATLIST'].fields_by_name['value']._loaded_options = None
  _globals['_FLOATLIST'].fields_by_name['value']._serialized_options = b'\020\001'
  _globals['_INT64LIST'].fields_by_name['value']._loaded_options = None
  _globals['_INT64LIST'].fields_by_name['value']._serialized_options = b'\020\001'
  _globals['_FEATURES_FEATUREENTRY']._loaded_options = None
  _globals['_FEATURES_FEATUREENTRY']._serialized_options = b'8\001'
  _globals['_FEATURELISTS_FEATURELISTENTRY']._loaded_options = None
  _globals['_FEATURELISTS_FEATURELISTENTRY']._serialized_options = b'8\001'
  _globals['_BYTESLIST']._serialized_start=33
  _globals['_BYTESLIST']._serialized_end=59
  _globals['_FLOATLIST']._serialized_start=61
  _globals['_FLOATLIST']._serialized_end=91
  _globals['_INT64LIST']._serialized_start=93
  _globals['_INT64LIST']._serialized_end=123
  _globals['_FEATURE']._serialized_start=126
  _globals['_FEATURE']._serialized_end=290
  _globals['_FEATURES']._serialized_start=293
  _globals['_FEATURES']._serialized_end=432
  _globals['_FEATURES_FEATUREENTRY']._serialized_start=361
  _globals['_FEATURES_FEATUREENTRY']._serialized_end=432
  _globals['_FEATURELIST']._serialized_start=434
  _globals['_FEATURELIST']._serialized_end=489
  _globals['_FEATURELISTS']._serialized_start=492
  _globals['_FEATURELISTS']._serialized_end=656
  _globals['_FEATURELISTS_FEATURELISTENTRY']._serialized_start=577
  _globals['_FEATURELISTS_FEATURELISTENTRY']._serialized_end=656
# @@protoc_insertion_point(module_scope)
