# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: numpyobject.proto
# Protobuf Python Version: 5.27.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    0,
    '',
    'numpyobject.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11numpyobject.proto\x12\x0e\x64\x61ta_serialize\"\x87\x01\n\x0bNumpyObject\x12\x0e\n\x06header\x18\x01 \x01(\t\x12\r\n\x05shape\x18\x02 \x03(\x03\x12\r\n\x05\x64type\x18\x03 \x01(\t\x12\r\n\x05\x62ytes\x18\x04 \x01(\x0c\x12\x11\n\x05int64\x18\x05 \x03(\x03\x42\x02\x10\x01\x12\x13\n\x07\x66loat32\x18\x06 \x03(\x02\x42\x02\x10\x01\x12\x13\n\x07\x66loat64\x18\x07 \x03(\x01\x42\x02\x10\x01\"\xaa\x01\n\x0eNumpyObjectMap\x12\x46\n\x0cnumpyobjects\x18\x01 \x03(\x0b\x32\x30.data_serialize.NumpyObjectMap.NumpyobjectsEntry\x1aP\n\x11NumpyobjectsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12*\n\x05value\x18\x02 \x01(\x0b\x32\x1b.data_serialize.NumpyObject:\x02\x38\x01\"D\n\x0fNumpyObjectList\x12\x31\n\x0cnumpyobjects\x18\x01 \x03(\x0b\x32\x1b.data_serialize.NumpyObjectb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'numpyobject_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NUMPYOBJECT'].fields_by_name['int64']._loaded_options = None
  _globals['_NUMPYOBJECT'].fields_by_name['int64']._serialized_options = b'\020\001'
  _globals['_NUMPYOBJECT'].fields_by_name['float32']._loaded_options = None
  _globals['_NUMPYOBJECT'].fields_by_name['float32']._serialized_options = b'\020\001'
  _globals['_NUMPYOBJECT'].fields_by_name['float64']._loaded_options = None
  _globals['_NUMPYOBJECT'].fields_by_name['float64']._serialized_options = b'\020\001'
  _globals['_NUMPYOBJECTMAP_NUMPYOBJECTSENTRY']._loaded_options = None
  _globals['_NUMPYOBJECTMAP_NUMPYOBJECTSENTRY']._serialized_options = b'8\001'
  _globals['_NUMPYOBJECT']._serialized_start=38
  _globals['_NUMPYOBJECT']._serialized_end=173
  _globals['_NUMPYOBJECTMAP']._serialized_start=176
  _globals['_NUMPYOBJECTMAP']._serialized_end=346
  _globals['_NUMPYOBJECTMAP_NUMPYOBJECTSENTRY']._serialized_start=266
  _globals['_NUMPYOBJECTMAP_NUMPYOBJECTSENTRY']._serialized_end=346
  _globals['_NUMPYOBJECTLIST']._serialized_start=348
  _globals['_NUMPYOBJECTLIST']._serialized_end=416
# @@protoc_insertion_point(module_scope)
